language: node_js

jobs: 
  include:
  # - stage: test
  #   scripts:
  #     - npm run test
  - name: Lint job
    node_js: '12'
    scripts: npm run lint:dry || exit 0
  # - name: Audit job
  #   node_js: '12'
  #   scripts: npm audit --audit-level=high
  - name: depcheck job
    node_js: '12'
    scripts: 
      - npm install -g depcheck
      - depcheck
  - name: outdated job
    node_js: '12'
    scripts: npm outdated
  - name: build job
    node_js: '12'
    scripts:
      - npm run build
      - ls -al
