language: node_js
node_js:
  # - node
  # - lts/*
  - 12

cache:
  npm: true

before_install:
- echo before_install
- chmod +x ./scripts/env.sh
- ./scripts/env.sh ${TRAVIS_BRANCH}

install: # main phase
- echo install

before_script:
- echo before_script

script: # main phase
- ls -al
# - npm run test
# - npm run lint
- if [ ${TRAVIS_BRANCH} == "master" ]; then
    echo copy lab parameters;
    cp ./parameters-dev.json ./parameters.json;
  elif [ ${TRAVIS_BRANCH} == "stg" ]; then
    echo copy staging parameters
    cp ./parameters-stg.json ./parameters.json;
  elif [ ${TRAVIS_BRANCH} == "prod" ]; then
    echo copy production parameters
    cp ./parameters-prod.json ./parameters.json;
  else
    echo do nothing;
  fi
- ls -al
- cat parameters.json
- printenv
  
after_success:
  - echo after_success

after_failure:
  - echo after_failure

after_script:
  - echo after_script
