language: node_js

node_js:
  - 12

cache: npm # cache $HOME/.npm

before_install:
- echo before_install
- chmod +x ./scripts/env.sh
- ./scripts/env.sh ${TRAVIS_BRANCH}
- chmod +x ./scripts/travis.sh
- ./scripts/travis.sh

install: # main phase
- echo install
- npm install

before_script:
- echo before_script

script: # main phase
- npm run build

after_script:
- ls -al

after_success:
- echo after_success

after_failure:
- echo after_failure