language: node_js
node_js:
  - node
  - lts/*
  - 14
  - 13
  - 12
  - 11
  - 10
before_install:
  - echo before_install

install:
  - npm install

before_script:
  - echo before_script

script:
  - ls -al

after_script:
  - echo after_script
  
after_success:
  - echo after_success
