language: node_js

node_js:
  - 12

cache: npm # cache $HOME/.npm

before_install:
- echo before_install
- chmod +x ./scripts/env.sh
- ./scripts/env.sh ${TRAVIS_BRANCH}
- chmod +x ./scripts/travis.sh
- ./scripts/travis.sh

install: # main phase
- echo install
# - npm install

before_script:
- echo before_script

script: # main phase
# - npm run build
- zip -r -q src.zip src public
- zip -r -q doc.zip *.md
- mkdir upload
- mv *.zip upload/

after_script:
- ls -al

after_success:
- echo after_success

after_failure:
- echo after_failure

deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  skip_cleanup: true
  bucket: $S3_BUCKET_NAME
  local_dir: upload
  region: us-east-1
  on:
    branch:
      travis