language: node_js
node_js:
  # - node
  # - lts/*
  # - 14
  # - 13
  - 12
  # - 11
  # - 10
cache:
  npm: true
  directories:
    - $HOME/vincent

before_install:
- echo before_install
# - mkdir -p $HOME/vincent

install:
- echo install
# - npm install

before_script:
- echo before_script

script:
- ls -al
# - npm run test
# - npm run lint
- if [ ${TRAVIS_BRANCH} == "master" ]; then
    echo copy lab parameters;
    cp ./parameters-dev.json ./parameters.json;
  elif [ ${TRAVIS_BRANCH} == "stg" ]; then
    echo copy staging parameters
    cp ./parameters-stg.json ./parameters.json;
  elif [ ${TRAVIS_BRANCH} == "prod" ]; then
    echo copy production parameters
    cp ./parameters-prod.json ./parameters.json;
  else
    echo do nothing;
  fi
- ls -al
- cat parameters.json
- less parameters.json

# jobs:
#   include:
#     - stage: setup files
#       script:
#         - echo $TRAVIS_BUILD_NUMBER
#         - echo oneone | tee > $HOME/vincent/one
#     - stage: setup files
#       script:
#         - echo $TRAVIS_BUILD_NUMBER
#         - echo twotwo | tee > $HOME/vincent/two
#     - stage: use shared files
#       script:
#         - echo $TRAVIS_BUILD_NUMBER
#         - ls -al
#         - ls -al $HOME/vincent
#         - tail -n +1 $HOME/vincent/*
#       after_success:
#           - echo job after_success

after_script:
  - echo after_script
  
after_success:
  - echo after_success
